substitute = (node) ->
  replacements = [
    # http://www.xkcd.com/1288
    ['Keyboard', 'Leopard']
    ['KEYBOARD', 'LEOPARD']
    ['keyboard', 'leopard']
    ['Keyboards', 'Leopards']
    ['KEYBOARDS', 'LEOPARDS']
    ['keyboards', 'leopards']
    ['Witnesses', 'These dudes I know']
    ['WITNESSES', 'THESE DUDES I KNOW']
    ['witnesses', 'these dudes I know']
    ['Witness', 'This dude I know']
    ['WITNESS', 'THIS DUDE I KNOW']
    ['witness', 'this dude I know']
    ['Allegedly', 'Kinda Probably']
    ['ALLEGEDLY', 'KINDAPROBABLY']
    ['allegedly', 'kinda probably']
    ['New Study', 'Tumblr Post']
    ['NEW STUDY', 'TUMBLR POST']
    ['new study', 'tumblr post']
    ['Rebuild', 'Avenge']
    ['REBUILD', 'AVENGE']
    ['rebuild', 'avenge']
    ['Space', 'Spaaaaaace']
    ['SPACE', 'SPAAAAAACE']
    ['space', 'spaaaaaace']
    ['Google Glass', 'Virtual Boy']
    ['GOOGLE GLASS', 'VIRTUAL BOY']
    ['google glass', 'virtual boy']
    ['Smartphone', 'Pok\u00E9dex']
    ['SMARTPHONE', 'POK\u00C9DEX']
    ['smartphone', 'pok\u00E9dex']
    ['Electric', 'Atomic']
    ['ELECTRIC', 'ATOMIC']
    ['electric', 'atomic']
    ['Senator', 'Elf-Lord']
    ['SENATOR', 'ELF-LORD']
    ['senator', 'elf-lord']
    ['Senators', 'Elf-Lords']
    ['SENATORS', 'ELF-LORDS']
    ['senators', 'elf-lords']
    ['Car', 'Cat']
    ['CAR', 'CAT']
    ['car', 'cat']
    ['Cars', 'Cats']
    ['CARS', 'CATS']
    ['cars', 'cats']
    ['Election', 'Eating Contest']
    ['ELECTION', 'EATING CONTEST']
    ['election', 'eating contest']
    ['Elections', 'Eating Contests']
    ['ELECTIONS', 'EATING CONTESTS']
    ['elections', 'eating contests']
    ['Congressional Leaders', 'River Spirits']
    ['CONGRESSIONAL LEADERS', 'RIVER SPIRITS']
    ['congressional leaders', 'river spirits']
    ['Homeland Security', 'Homestar Runner']
    ['HOMELAND SECURITY', 'HOMESTAR RUNNER']
    ['homeland security', 'homestar runner']
    ['Homeland security', 'Homestar runner']
    ['Could not be reached for comment', 'Is guilty and everyone knows it']
    ['COULD NOT BE REACHED FOR COMMENT', 'IS GUILTY AND EVERYONE KNOWS IT']
    ['Could Not Be Reached For Comment', 'Is Guilty And Everyone Knows It']
    ['could not be reached for comment', 'is guilty and everyone knows it']
    # http://xkcd.com/1418/
    ['Force', 'Horse']
    ['FORCE', 'HORSE']
    ['force', 'horse']
    ['Forces', 'Horses']
    ['FORCES', 'HORSES']
    ['forces', 'horses']
    # http://xkcd.com/1625
    ['Debate', "Dance-off"]
    ['DEBATE', "DANCE-OFF"]
    ['debate', "dance-off"]
    ['Self driving', 'Uncontrollably swerving']
    ['SELF DRIVING', 'UNCONTROLLABLY SWERVING']
    ['self driving', 'uncontrollably swerving']
    ['Poll', 'Psychic reading']
    ['POLL', 'PSYCHIC READING']
    ['poll', 'psychic reading']
    ['Candidate', 'Airbender']
    ['CANDIDATE', 'AIRBENDER']
    ['candidate', 'airbender']
    ['Drone', 'Dog']
    ['DRONE', 'DOG']
    ['drone', 'dog']
    ['Vows to', 'Probably won\'t']
    ['VOWS TO', 'PROBABLY WON\'T']
    ['vows to', 'probably won\'t']
    ['At large', 'Very large']
    ['AT LARGE', 'VERY LARGE']
    ['at large', 'very large']
    ['Successfully', 'Suddenly']
    ['SUCCESSFULLY', 'SUDDENLY']
    ['successfully', 'suddenly']
    ['Expands', 'Physically expands']
    ['EXPANDS', 'PHYSICALLY EXPANDS']
    ['expands', 'physically expands']
    ['First-degree', 'Friggin\' awful']
    ['FIRST-DEGREE', 'FRIGGIN\' AWFUL']
    ['first-degree', 'friggin\' awful']
    ['Second-degree', 'Friggin\' awful']
    ['SECOND-DEGREE', 'FRIGGIN\' AWFUL']
    ['second-degree', 'friggin\' awful']
    ['Third-degree', 'Friggin\' awful']
    ['THIRD-DEGREE', 'FRIGGIN\' AWFUL']
    ['third-degree', 'friggin\' awful']
    ['An unknown number', 'Like hundreds']
    ['AN UNKNOWN NUMBER', 'LIKE HUNDREDS']
    ['an unknown number', 'like hundreds']
    ['Front runner', 'Blade runner']
    ['FRONT RUNNER', 'BLADE RUNNER']
    ['front runner', 'blade runner']
    ['Global', 'Spherical']
    ['GLOBAL', 'SPHERICAL']
    ['global', 'spherical']
    ['Minutes', 'Years']
    ['MINUTES', 'YEARS']
    ['minutes', 'years']
    ['Years', 'Minutes']
    ['YEARS', 'MINUTES']
    ['years', 'minutes']
    ['No indication', 'Lots of signs']
    ['NO INDICATION', 'LOTS OF SIGNS']
    ['no indication', 'lots of signs']
    ['Urged restraint by', 'Drunkenly egged on']
    ['URGED RESTRAINT BY', 'DRUNKENLY EGGED ON']
    ['urged restraint by', 'drunkenly egged on']
    ['Horsepower', 'Tons of horsemeat']
    ['HORSEPOWER', 'TONS OF HORSEMEAT']
    ['horsepower', 'tons of horsemeat']
    # https://xkcd.com/1004
    ["Batman", "A man dressed like a bat"]
    ["BATMAN", "A MAN DRESSED LIKE A BAT"]
    ["batman", "a man dressed like a bat"]
  ]

  ignore = ['STYLE', 'SCRIPT', 'NOSCRIPT', 'IFRAME', 'OBJECT', 'INPUT', 'FORM', 'TEXTAREA']
  if node.tagName in ignore then return

  for replacement in replacements
    original = RegExp "\\b#{replacement[0]}\\b", 'g'
    node.data = node.data.replace original, replacement[1]

# Here we go
iter = document.createNodeIterator document.body, NodeFilter.SHOW_TEXT

while node = iter.nextNode()
  substitute node

