substitute = (node) ->
  replacements = [
    # http://www.xkcd.com/1288
    ['Keyboard', 'Leopard']
    ['KEYBOARD', 'LEOPARD']
    ['keyboard', 'leopard']
    ['Keyboards', 'Leopards']
    ['KEYBOARDS', 'LEOPARDS']
    ['keyboards', 'leopards']
    ['Witnesses', 'These dudes I know']
    ['WITNESSES', 'THESE DUDES I KNOW']
    ['witnesses', 'these dudes I know']
    ['Witness', 'This dude I know']
    ['WITNESS', 'THIS DUDE I KNOW']
    ['witness', 'this dude I know']
    ['Allegedly', 'Kinda Probably']
    ['ALLEGEDLY', 'KINDAPROBABLY']
    ['allegedly', 'kinda probably']
    ['New Study', 'Tumblr Post']
    ['NEW STUDY', 'TUMBLR POST']
    ['new study', 'tumblr post']
    ['Rebuild', 'Avenge']
    ['REBUILD', 'AVENGE']
    ['rebuild', 'avenge']
    ['Space', 'Spaaaaaace']
    ['SPACE', 'SPAAAAAACE']
    ['space', 'spaaaaaace']
    ['Google Glass', 'Virtual Boy']
    ['GOOGLE GLASS', 'VIRTUAL BOY']
    ['google glass', 'virtual boy']
    ['Smartphone', 'Pok\u00E9dex']
    ['SMARTPHONE', 'POK\u00C9DEX']
    ['smartphone', 'pok\u00E9dex']
    ['Electric', 'Atomic']
    ['ELECTRIC', 'ATOMIC']
    ['electric', 'atomic']
    ['Senator', 'Elf-Lord']
    ['SENATOR', 'ELF-LORD']
    ['senator', 'elf-lord']
    ['Senators', 'Elf-Lords']
    ['SENATORS', 'ELF-LORDS']
    ['senators', 'elf-lords']
    ['Car', 'Cat']
    ['CAR', 'CAT']
    ['car', 'cat']
    ['Cars', 'Cats']
    ['CARS', 'CATS']
    ['cars', 'cats']
    ['Election', 'Eating Contest']
    ['ELECTION', 'EATING CONTEST']
    ['election', 'eating contest']
    ['Elections', 'Eating Contests']
    ['ELECTIONS', 'EATING CONTESTS']
    ['elections', 'eating contests']
    ['Congressional Leaders', 'River Spirits']
    ['CONGRESSIONAL LEADERS', 'RIVER SPIRITS']
    ['congressional leaders', 'river spirits']
    ['Homeland Security', 'Homestar Runner']
    ['HOMELAND SECURITY', 'HOMESTAR RUNNER']
    ['homeland security', 'homestar runner']
    ['Homeland security', 'Homestar runner']
    ['Could not be reached for comment', 'Is guilty and everyone knows it']
    ['COULD NOT BE REACHED FOR COMMENT', 'IS GUILTY AND EVERYONE KNOWS IT']
    ['Could Not Be Reached For Comment', 'Is Guilty And Everyone Knows It']
    ['could not be reached for comment', 'is guilty and everyone knows it']
    # http://xkcd.com/1418/
    ['Force', 'Horse']
    ['FORCE', 'HORSE']
    ['force', 'horse']
    ['Forces', 'Horses']
    ['FORCES', 'HORSES']
    ['forces', 'horses']
    # http://xkcd.com/1625
    ['Debate', "Dance-off"]
    ['DEBATE', "DANCE-OFF"]
    ['debate', "dance-off"]
    ['Self driving', 'Uncontrollably swerving']
    ['SELF DRIVING', 'UNCONTROLLABLY SWERVING']
    ['self driving', 'uncontrollably swerving']
    ['Poll', 'Psychic reading']
    ['POLL', 'PSYCHIC READING']
    ['poll', 'psychic reading']
    ['Candidate', 'Airbender']
    ['CANDIDATE', 'AIRBENDER']
    ['candidate', 'airbender']
    ['Drone', 'Dog']
    ['DRONE', 'DOG']
    ['drone', 'dog']
    ['Vows to', 'Probably won\'t']
    ['VOWS TO', 'PROBABLY WON\'T']
    ['vows to', 'probably won\'t']
    ['At large', 'Very large']
    ['AT LARGE', 'VERY LARGE']
    ['at large', 'very large']
    ['Successfully', 'Suddenly']
    ['SUCCESSFULLY', 'SUDDENLY']
    ['successfully', 'suddenly']
    ['Expands', 'Physically expands']
    ['EXPANDS', 'PHYSICALLY EXPANDS']
    ['expands', 'physically expands']
    ['First-degree', 'Friggin\' awful']
    ['FIRST-DEGREE', 'FRIGGIN\' AWFUL']
    ['first-degree', 'friggin\' awful']
    ['Second-degree', 'Friggin\' awful']
    ['SECOND-DEGREE', 'FRIGGIN\' AWFUL']
    ['second-degree', 'friggin\' awful']
    ['Third-degree', 'Friggin\' awful']
    ['THIRD-DEGREE', 'FRIGGIN\' AWFUL']
    ['third-degree', 'friggin\' awful']
    ['An unknown number', 'Like hundreds']
    ['AN UNKNOWN NUMBER', 'LIKE HUNDREDS']
    ['an unknown number', 'like hundreds']
    ['Front runner', 'Blade runner']
    ['FRONT RUNNER', 'BLADE RUNNER']
    ['front runner', 'blade runner']
    ['Global', 'Spherical']
    ['GLOBAL', 'SPHERICAL']
    ['global', 'spherical']
    ['Minutes', 'Years']
    ['MINUTES', 'YEARS']
    ['minutes', 'years']
    ['Years', 'Minutes']
    ['YEARS', 'MINUTES']
    ['years', 'minutes']
    ['No indication', 'Lots of signs']
    ['NO INDICATION', 'LOTS OF SIGNS']
    ['no indication', 'lots of signs']
    ['Urged restraint by', 'Drunkenly egged on']
    ['URGED RESTRAINT BY', 'DRUNKENLY EGGED ON']
    ['urged restraint by', 'drunkenly egged on']
    ['Horsepower', 'Tons of horsemeat']
    ['HORSEPOWER', 'TONS OF HORSEMEAT']
    ['horsepower', 'tons of horsemeat']
    # https://xkcd.com/1004
    ["Batman", "A man dressed like a bat"]
    ["BATMAN", "A MAN DRESSED LIKE A BAT"]
    ["batman", "a man dressed like a bat"]
    # http://xkcd.com/1679
    ['Gaffe', 'Magic spell']
    ['GAFFE', 'MAGIC SPELL']
    ['gaffe', 'magic spell']
    ['Gaffes', 'Magic spells']
    ['GAFFEs', 'MAGIC SPELLS']
    ['gaffes', 'magic spells']
    ['Ancient', 'Haunted']
    ['ANCIENT', 'HAUNTED']
    ['ancient', 'haunted']
    ['Star-studded', 'Blood-soaked']
    ['STAR-STUDDED', 'BLOOD-SOAKED']
    ['star-studded', 'blood-soaked']
    ['Star-Studded', 'Blood-Soaked']
    ['Star studded', 'Blood soaked']
    ['STAR STUDDED', 'BLOOD SOAKED']
    ['star studded', 'blood soaked']
    ['Star Studded', 'Blood Soaked']
    ['Remains to be seen', 'Will never be known']
    ['REMAINS TO BE SEEN', 'WILL NEVER BE KNOWN']
    ['remains to be seen', 'will never be known']
    ['Remains to be Seen', 'Will Never be Known']
    ['Silver bullet', 'Way to kill werewolves']
    ['SILVER BULLET', 'WAY TO KILL WEREWOLVES']
    ['silver bullet', 'way to kill werewolves']
    ['Silver Bullet', 'Way to Kill Werewolves']
    ['Silver bullets', 'Ways to kill werewolves']
    ['SILVER BULLETS', 'WAYS TO KILL WEREWOLVES']
    ['silver bullets', 'ways to kill werewolves']
    ['Silver Bullets', 'Ways to Kill Werewolves']
    ['Subway system', 'Tunnels I found']
    ['SUBWAY SYSTEM', 'TUNNELS I FOUND']
    ['subway system', 'tunnels I found']
    ['Subway System', 'Tunnels I Found']
    ['Surprising', 'Surprising (but not for me)']
    ['SURPRISING', 'SURPRISING (BUT NOT FOR ME)']
    ['surprising', 'surprising (but not for me)']
    ['War of words', 'Interplanetary war']
    ['WAR OF WORDS', 'INTERPLANETARY WAR']
    ['war of words', 'interplanetary war']
    ['Tension', 'Sexual tension']
    ['TENSION', 'SEXUAL TENSION']
    ['tension', 'sexual tension']
    ['Tensions', 'Sexual tensions']
    ['TENSIONS', 'SEXUAL TENSIONS']
    ['tensions', 'sexual tensions']
    ['Cautiosly optomistic', 'Delusional']
    ['CAUTIOSLY OPTOMISTIC', 'DELUSIONAL']
    ['cuatiosly optomistic', 'delusional']
    ['Doctor Who', 'The Big Bang Theory']
    ['DOCTOR WHO', 'THE BIG BANG THEORY']
    ['doctor who', 'the big bang theory']
    ['Win votes', 'Find Pokémon']
    ['WIN VOTES', 'FIND POKÉMON']
    ['win votes', 'find Pokémon']
    ['Winning votes', 'Finding Pokémon']
    ['WINNING VOTES', 'FINDING POKÉMON']
    ['winning votes', 'finding Pokémon']
    ['Winning Votes', 'Finding Pokémon']
    ['Behind the headlines', 'Beyond the grave']
    ['BEHIND THE HEADLINES', 'BEYOND THE GRAVE']
    ['behind the headlines', 'beyond the grave']
    ['Behind the Headlines', 'Beyond the Grave']
    ['Email', 'Poem']
    ['EMAIL', 'POEM']
    ['email', 'poem']
    ['Emails', 'Poems']
    ['EMAILS', 'POEMS']
    ['emails', 'poems']
    ['Facebook Post', 'Poem']
    ['Facebook post', 'Poem']
    ['FACEBOOK POST', 'POEM']
    ['facebook post', 'poem']
    ['Facebook Posts', 'Poems']
    ['FACEBOOK POSTS', 'POEMS']
    ['facebook posts', 'poems']
    ['Tweet', 'Poem']
    ['TWEET', 'POEM']
    ['tweet', 'poem']
    ['Tweets', 'Poems']
    ['TWEETS', 'POEMS']
    ['tweets', 'poems']
    ['Facebook CEO', 'This guy']
    ['FACEBOOK CEO', 'THIS GUY']
    ['facebook CEO', 'this guy']
    ['Latest', 'Final']
    ['LATEST', 'FINAL']
    ['latest', 'final']
    ['Disrupt', 'Destroy']
    ['DISRUPT', 'DESTROY']
    ['disrupt', 'destroy']
    ['Disrupted', 'Destroyed']
    ['DISRUPTED', 'DESTROYED']
    ['disrupted', 'destroyed']
    ['Disrupting', 'Destroying']
    ['DISRUPTING', 'DESTROYING']
    ['disrupting', 'destroying']
    ['Meeting', 'Ménage à trois']
    ['MEETING' ,'MÉNAGE À TROIS']
    ['meeting', 'ménage à trois']
    ['Scientists', 'Channing Tatum and his friends']
    ['SCIENTISTS', 'CHANNING TATUM AND HIS FRIENDS']
    ['scientists', 'Channing Tatum and his friends']
    ["You won't believe", "I'm really sad about"]
    ["YOU WON'T BELIEVE", "I'M REALLY SAD ABOUT"]
    ["you won't believe", "I'm really sad about"]
    ["You Won't Believe", "I'm Really Sad About"]
  ]

  ignore = ['STYLE', 'SCRIPT', 'NOSCRIPT', 'IFRAME', 'OBJECT', 'INPUT', 'FORM', 'TEXTAREA']
  if node.tagName in ignore then return

  for replacement in replacements
    original = RegExp "\\b#{replacement[0]}\\b", 'g'
    node.data = node.data.replace original, replacement[1]

# Here we go
iter = document.createNodeIterator document.body, NodeFilter.SHOW_TEXT

while node = iter.nextNode()
  substitute node

